name: Shell Workflow
on:
  push:
    branches:
      - 'ci/**'
  
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Check scripts
        run: |
          echo "checking scripts:"
          shellcheck scripts/*.sh
