name: Shell Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: check files
        run: ls
      - name: Check scripts
        run: |
          echo "checking scripts:"
          shellcheck scripts/*.sh
